# Generated by Django 3.0.8 on 2020-10-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='LinkTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='form',
            name='tag',
            field=models.ManyToManyField(to='api.FormTags'),
        ),
        migrations.AddField(
            model_name='link',
            name='tag',
            field=models.ManyToManyField(to='api.LinkTags'),
        ),
    ]
