# Generated by Django 3.0.8 on 2020-10-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201005_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
