# Generated by Django 3.0.8 on 2020-10-12 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201008_1155'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Link',
        ),
        migrations.DeleteModel(
            name='LinkTags',
        ),
    ]
