# Generated by Django 3.1 on 2020-12-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='content',
            name='active',
        ),
        migrations.RemoveField(
            model_name='content',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='content',
            name='name',
        ),
        migrations.RemoveField(
            model_name='content',
            name='path',
        ),
        migrations.RemoveField(
            model_name='content',
            name='size',
        ),
        migrations.RemoveField(
            model_name='content',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='content',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='content',
            name='uploaded',
        ),
        migrations.RemoveField(
            model_name='content',
            name='user',
        ),
        migrations.AddField(
            model_name='content',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='file',
            field=models.FileField(null=True, upload_to='documents/training/'),
        ),
        migrations.AddField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='subject',
            field=models.ManyToManyField(to='api.Subject'),
        ),
    ]
