# Generated by Django 3.1 on 2020-12-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201202_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, null=True)),
                ('file', models.FileField(null=True, upload_to='documents/')),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
