# Generated by Django 3.1 on 2020-12-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_form2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form2',
            name='file',
            field=models.FileField(null=True, upload_to='documents/resourceForms/'),
        ),
    ]
