# Generated by Django 3.1 on 2020-12-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201210_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='documents/training/'),
        ),
    ]
