# Generated by Django 3.1 on 2021-01-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='speciality',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
