# Generated by Django 3.1 on 2021-01-12 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
