# Generated by Django 3.0.8 on 2020-10-13 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_methods'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Methods',
        ),
    ]
