# Generated by Django 3.1 on 2020-12-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='text2',
            field=models.TextField(null=True),
        ),
    ]
